# 服务端口号
server:
  port: 8004

spring:
  application:
    name: sanxin-cloud-images # 对外暴露的服务名称
  resources:
    static-locations: classpath:/files/,file:files/
  mvc:
    static-path-pattern: /files/**
# 客户端注册进eureka服务列表里
eureka:
  client:
    service-url:
      defaultZone: http://47.244.167.166:7001/eureka/,http://47.244.167.166:7002/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: 图片管理  # 人性化显示出服务的信息
    prefer-ip-address: true    # 访问路径可显示ip地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    ip-address: 127.0.0.1
# 使用actuator来展示项目的基本信息
info:
  author.name: Arno
  app.name: 三心网络科技
