# 服务端口号
server:
  port: 8003

spring:
  application:
    name: sanxin-cloud-netty # 对外暴露的服务名称
  datasource: # 数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://183.60.136.220:3306/powerplus?useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false
    username: root
    password: rhzh
    #下半区属性对应的是 com.alibaba.druid.pool.DruidDataSource 中的属性，Spring Boot 默认是不注入不了这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  redis:
    host: 183.60.136.220
    port: 6388
    token:
      time: 864000
    password:
    jedis:
      pool:
        max-wait: 1000ms
        max-active: 600
        max-idle: 300

mybatis-plus:
  mapper-locations:  classpath:mybatis/mapper/*.xml
  type-aliases-package: com.sanxin.cloud.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    default-executor-type: reuse
    default-statement-timeout: 25000

# 客户端注册进eureka服务列表里
eureka:
  client:
    service-url:
      defaultZone: http://35.240.194.196:7001/eureka/,http://35.240.194.196:7002/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: netty-server  # 人性化显示出服务的信息
    prefer-ip-address: false    # 访问路径可显示ip地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

#netty
netty:
  port: 8086
  appPort: 8087

# 使用actuator来展示项目的基本信息
info:
  author.name: Arno
  app.name: 三心网络科技
