# 服务端口号
server:
  port: 6001

spring:
  application:
    name: sanxin-cloud-gateway # 对外暴露的服务名称

# 客户端注册进eureka服务列表里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: 三心网关路由服务  # 人性化显示出服务的信息
    prefer-ip-address: false    # 访问路径可显示ip地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

# 使用actuator来展示项目的基本信息
info:
  author.name: Arno
  app.name: 三心网络科技

# 配置路由规则
zuul:
  # 不允许用微服务名访问了，如果禁用所有的，可以使用 "*"
  ignored-services: "*"
  routes:
    # 给路由加一个统一的前缀
    prefix: /zuul
    # 如下指定新的映射
    admin-api:
      serviceId: sanxin-cloud-admin-api
      path: /admin/**
#      stripPrefix: false

